//
//  SearchPresenter.swift
//  Assesment Test
//
//  Created by Kalyan Thakur on 23/03/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchPresenterInput
{
    func presentBlockDataFromJson(units:[UnitsParse])
    func presentSearchResult(units:[UnitsParse]?)
}

protocol SearchPresenterOutput: class
{
    func displayBlockDataFromJson(units:[UnitsParse])
    func displaySearchResult(units:[UnitsParse]?)
}

class SearchPresenter: SearchPresenterInput
{
    weak var viewController: SearchPresenterOutput?
    func presentBlockDataFromJson(units: [UnitsParse]) {
        viewController?.displayBlockDataFromJson(units: units)
    }
    
    func presentSearchResult(units: [UnitsParse]?) {
        viewController?.displaySearchResult(units: units)
    }
}
